redirection to githubpage
RealDevSquad/mobile-app pull request #203
Opened 2023-08-20 06:55 UTC by shreya-mishra

2023-08-20 15:22 UTC, biswanathTewari requested changes, later dismissed

2023-08-20 15:22 UTC, biswanathTewari commented on src/screens/AuthScreen/AuthScreen.tsx
> +  'https://github.com/login/oauth/authorize?client_id=YOUR_CLIENT_ID&redirect_uri=yourappname://oauth&scope=user';
placeholders needs to be replaced with actual values

2023-09-20 16:02 UTC, prudhvir3ddy commented on android/app/src/main/java/com/rdsapp/MainActivity.java
> +    Uri appLinkData = appLinkIntent.getData();
Not seeing any usage of this. 

I hope react native linking APIs provides this data in typescript files itself 

if it is then we can remove this code

2023-09-20 16:17 UTC, shreya-mishra commented on android/app/src/main/java/com/rdsapp/MainActivity.java
> +    Uri appLinkData = appLinkIntent.getData();
This is automatically linked while implementing app links deeplinking process.


Doesnt matter for now I guess nothing is working as expected

2023-09-20 17:16 UTC, prudhvir3ddy commented on config/config.js
> +export const clientId = '23c78f66ab7964e5ef97';
with the given client ID, i am seeing the callback URL is 
`https://api.realdevsquad.com/auth/github/callback`

check same in developer settings of the GitHub 

we are not handling this URL in the app and path in AndroidManifest.xml 

we need to handle this path

2023-09-27 19:19 UTC, ashifkhn commented
I have installed the app locally from the branch it keeps loading after signing in. It redirects me to the app. So the redirection is working fine.

2023-09-28 08:19 UTC, shreya-mishra commented
> I have installed the app locally from the branch it keeps loading after signing in. It redirects me to the app. So the redirection is working fine.

check the recent code ! it worked fine now.

2023-09-28 11:41 UTC, sahsisunny approved these changes

2023-09-28 12:09 UTC, merged