Feature/environment setup
RealDevSquad/mobile-app pull request #205
Opened 2023-08-21 15:14 UTC by mohammadkhizerkhan

This PR contains

- different env files for different environments
- scripts for running android, debug builds for different environments

2023-08-22 12:10 UTC, shreya-mishra reviewed
Please make this PR as WIP as prod release env has not setup

2023-09-06 23:51 UTC, sahsisunny commented on .gitignore
> +yarn.lock
Why?

2023-09-06 23:52 UTC, sahsisunny commented on .env
> +# API_URL= https://api.realdevsquad.com/
you can add the default local URL here.

2023-09-06 23:52 UTC, sahsisunny commented on android/app/build.gradle
Why so many comments here?

2023-09-06 23:57 UTC, sahsisunny requested changes
This pull request is intended for staging environment, but I noticed that it contains changes that alter the context of the request. Can you explain why?

2023-09-07 08:27 UTC, mohammadkhizerkhan commented
> This pull request is intended for staging environment, but I noticed that it contains changes that alter the context of the request. Can you explain why?

can you please elaborate here?

2023-09-07 13:43 UTC, sahsisunny commented on .env
> +API_URL= http://localhost:3000/
```suggestion
API_URL= http://localhost:3000
```

2023-09-07 13:43 UTC, sahsisunny commented on .env.staging
> +API_URL= https://staging-api.realdevsquad.com/
```suggestion
API_URL= https://staging-api.realdevsquad.com
```

2023-09-07 13:43 UTC, sahsisunny commented on .env.production
> +API_URL= https://api.realdevsquad.com/
```suggestion
API_URL= https://api.realdevsquad.com
```

2023-09-07 13:45 UTC, sahsisunny commented on src/screens/AuthScreen/AuthScreen.tsx
> +        {/* <View style={AuthViewStyle.btnContainer}>
Could you please explain why you added a comment to this component?

2023-09-07 13:55 UTC, mohammadkhizerkhan commented
> This pull request is intended for staging environment, but I noticed that it contains changes that alter the context of the request. Can you explain why?

addressed this issue

2023-10-09 00:31 UTC, closed without merging