Notification/local notify
RealDevSquad/mobile-app pull request #453
Opened 2024-09-29 12:31 UTC by divyansh0908

Date: 

Developer Name: @divyansh0908

---

## Issue Ticket Number

https://github.com/Real-Dev-Squad/mobile-app/issues/438

## Description

This update marks the completion of the remaining tasks from [TCR](https://status.realdevsquad.com/tasks/ZRyXdtDmnEauzXOUn5eF). The rest of the changes made for this TCR can be found in this (https://github.com/Real-Dev-Squad/mobile-app/pull/439)[PR]. Additionally, This update also include a script that creates `google-services.json`, with support from env.

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-10-03 12:28 UTC, ashifkhn requested changes

2024-10-03 12:28 UTC, ashifkhn commented on src/components/Notify/NotifyForm.tsx
> +      console.log('🚀 ~ getFCMToken ~ fcmToken_:', fcmToken_);
Why are we keeping console here?

2024-10-03 12:28 UTC, ashifkhn commented on src/components/Notify/NotifyForm.tsx
> +      console.log('🚀 ~ getFCMToken ~ fcmToken_:', fcmToken_);
Please remove console.

2024-10-03 12:28 UTC, ashifkhn commented on src/screens/NotifyScreen/NotifyScreen.tsx
> +  title: {
There is the scale function for having responsive font, please use that.

2024-10-03 12:28 UTC, ashifkhn commented on src/service/googleServiceTemplate.js
> +console.log('🥲🥲🥲🥲🥲', googleServicesTemplate);
Please remove console.

2024-10-03 18:10 UTC, ashifkhn approved these changes

2024-10-04 19:23 UTC, yesyash approved these changes

2024-10-08 12:11 UTC, merged