fix(deps): update packages and modify Datepicker.tsx, Refs: #454,462
RealDevSquad/mobile-app pull request #463
Opened 2024-10-09 10:11 UTC by Aditys018

Date: 09-10-2024

Developer Name: Aditi Shinde

---

## Issue Ticket Number
#454 

## Description
This Updates the following packages from the package.json

• async-storage     • netinfo     • masked-view     • axios     • prettier     • app-auth     • tab-view     • image-picker     • keychain   • buttons-group    • safe-area-context     • react-native-svg     • react-redux     • align-deps      • jest-native     • jest     • react     • react-native      • eslint-parser     • eslint

Additionally updated DatePicker.tsx for compatibility with the updated dependencies (Refs: #462 )

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

[](https://github.com/user-attachments/assets/b3f51606-3ed4-4eb7-aae5-fc24b6da8549)

## Test Coverage
<details>
<summary>Screenshot 1</summary>
NA

</details>

## Additional Notes

2024-10-09 10:16 UTC, ashifkhn requested changes
Left few comments;

2024-10-09 10:16 UTC, ashifkhn commented on android/build.gradle
Why have you changed minSdkVersion?

2024-10-09 10:16 UTC, ashifkhn commented on android/gradle.properties
Why was this change needed?

2024-10-09 10:16 UTC, ashifkhn commented on src/components/CreateGoalForm/DatePicker.tsx
As per our discussion, we decided to remove this code in a separate pr.

2024-10-09 12:08 UTC, Ayushsanjdev requested changes

2024-10-09 12:08 UTC, Ayushsanjdev commented on android/build.gradle
This will lead to having issues on publishing it to playstore, should always use latest. @Aditys018 fyi

2024-10-09 13:07 UTC, shreya-mishra commented on src/components/CreateGoalForm/DatePicker.tsx
> +// import React, { useState } from 'react';
why are we commenting this file , if we are not using it please delete it

2024-10-13 03:24 UTC, shreya-mishra commented on package.json
> +    "@react-native-masked-view/masked-view": "^0.2.9",
can we pinned these versions as per our discussion ?

2024-11-08 16:46 UTC, ashifkhn approved these changes, later dismissed

2024-11-08 16:56 UTC, pankajjs approved these changes

2024-11-08 17:02 UTC, vinit717 commented
CI/CD build is failing and also add screenshot of working app build

2024-11-08 17:02 UTC, vinit717 requested changes
CI/CD build is failing and also add screenshot of working app build

2024-11-08 18:38 UTC, Aditys018 commented
@vinit717  CI Build is successful. 
Recording of the working app here : 
https://github.com/user-attachments/assets/33761aef-699b-44b5-9811-f3120e81344a

2024-11-08 18:50 UTC, vinit717 commented on package.json
> -    "@types/react-native-datepicker": "^1.7.1",
Are we not using it?

2024-11-08 21:21 UTC, Aditys018 commented
Resolved date-picker comment by @vinit717 


https://github.com/user-attachments/assets/ae222bc6-d020-4ed1-bb9e-6c1dea56568a

2024-11-09 13:34 UTC, ashifkhn approved these changes

2024-11-09 14:04 UTC, iamitprakash approved these changes

2024-11-09 14:04 UTC, merged