updated readme
RealDevSquad/mobile-app pull request #62
Opened 2022-02-22 09:55 UTC by shreya-mishra

2022-02-22 10:40 UTC, palakgupta2712 commented on README.md
> +- Discuss contribute and raise the PR.
Discuss, contribute and raise the PR.

2022-02-22 10:40 UTC, palakgupta2712 approved these changes

2022-02-22 10:42 UTC, palakgupta2712 requested changes
Update the line no 41

2022-02-22 20:24 UTC, shreya-mishra commented
> Update the line no 41

Resolved !

2022-03-07 16:53 UTC, palakgupta2712 approved these changes

2022-03-07 16:53 UTC, merged