Feat/profile screen
RealDevSquad/mobile-app pull request #78
Opened 2022-03-13 19:14 UTC by shreya-mishra

2022-03-16 19:35 UTC, palakgupta2712 commented on src/screens/ProfileScreen/styles.ts
> +    // backgroundColor: 'red',
remove unnecessary commented code

2022-03-16 19:48 UTC, palakgupta2712 requested changes
Please check package-lock.json

2022-03-17 16:47 UTC, shreya-mishra reviewed
removed the comments!

2022-03-19 16:09 UTC, palakgupta2712 approved these changes

2022-03-19 16:09 UTC, merged