fixed ui and started authentication
RealDevSquad/mobile-app pull request #79
Opened 2022-03-21 18:37 UTC by shreya-mishra

2022-03-21 18:45 UTC, DeRaowl requested changes

2022-03-21 18:45 UTC, DeRaowl commented on src/screens/AuthScreen/AuthScreen.tsx
> +      console.log('authState', authState);
Remove console statement.

2022-03-21 18:45 UTC, DeRaowl commented on src/screens/ProfileScreen/ProfileScreen.tsx
> +          // <Avatar uri={Images.DEFAULT_IMAGE} size={100} />
Remove commented code. And also  use ternary condition here

2022-03-21 18:45 UTC, DeRaowl commented on src/screens/ProfileScreen/ProfileScreen.tsx
> +        {/* {!response.hasOwnProperty('assets') && (
Please remove commented code.

2022-03-29 11:14 UTC, DeRaowl requested changes

2022-03-29 11:14 UTC, DeRaowl commented on src/context/AuthContext.js
> -export default AuthContext;
If we not using this file, please remove it.

2022-03-29 11:14 UTC, DeRaowl commented on src/context/AuthContext.tsx
> +      <>{children}</>
Why are we using React Fragments here?

2022-03-29 11:14 UTC, DeRaowl commented on __tests__/App-test.tsx
> +  const loggedInUserData = {name: 'shreya', profileUrl: ''};
Why userName is hardcoded here?

2022-03-29 11:14 UTC, DeRaowl commented on __tests__/App-test.tsx
> +                name: 'shreya',
Same here, the Username has been hardcoded.

2022-03-29 11:14 UTC, DeRaowl commented on __tests__/__snapshots__/HomeScreen-test.tsx.snap
> +            "paddingBottom": 20,
Can we reduce it to, paddingHorizontal and paddingVertical

2022-03-29 11:14 UTC, DeRaowl commented on src/constants/appConstant/url.ts
> +// import {githubConfig} from '../../../config/config'; // you can include client id from readme file in config
Remove this if it is not needed

2022-03-29 11:14 UTC, DeRaowl commented on src/screens/ProfileScreen/ProfileScreen.tsx
>    const openModal = useCallback(() => {
Why useCallback used here?

2022-03-31 09:41 UTC, vvaibhavdesai commented on src/screens/ProfileScreen/ProfileScreen.tsx
>    const [response, setResponse] = useState<any>({});
why are we not using a proper type for response type & instead using any here ?

2022-03-31 09:44 UTC, vvaibhavdesai commented on src/screens/ProfileScreen/ProfileScreen.tsx
> -      console.log('error', error);
instead of consoling these errors can we use a any sentry service to track these catch blocks?

2022-03-31 09:51 UTC, vvaibhavdesai commented on src/screens/AuthScreen/Util.ts
> +      .get(`https://api.realdevsquad.com/users/self`, {
we can assign variables to apis and use them respectively, the benefit of that would be changing those variable apis at one place would reflect across the app and become easier to work with!

2022-03-31 09:51 UTC, vvaibhavdesai commented on src/screens/AuthScreen/Util.ts
> +      .catch(err => Promise.reject(null));
why reject with a null and not a proper error?

2022-03-31 09:56 UTC, vvaibhavdesai commented on src/index.tsx
> +      {isLoading ? (
can we please move this to if-else which will improve the readability!

2022-03-31 10:02 UTC, vvaibhavdesai commented on src/context/AuthContext.tsx
> +export const AuthProvider = ({children}: any) => {
instead of any we can use { children }: { children: ReactNode }

2022-03-31 10:08 UTC, vvaibhavdesai reviewed
The rest of the PR looks good to me but there are a few things to iterate over which are suggested please get them resolved. Some more changes are also needed where at a lot of places we are using any which shall be changed to respective types.

2022-04-01 14:48 UTC, ankushdharkar commented on src/screens/ProfileScreen/ProfileScreen.tsx
> -      console.log('error', error);
or at least `console.error`

2022-04-01 15:00 UTC, ankushdharkar commented on src/index.tsx
> +};
```suggestion
const Index = () => {
  const {isLoading, loggedInUserData} = useContext(AuthContext);
  
  if (isLoading) {
    return <LoadingScreen />;
  }
  
  if(!loggedInUserData) {
    return <AuthScreen />;
  }
  
  return <TabNavigation />; // Should this be renamed to MainScreen? #TODO
};
```

2022-04-01 15:00 UTC, ankushdharkar commented on src/index.tsx
> +      {isLoading ? (
Good point @vvaibhavdesai. Nested ternary is harder to read for me too! 💯

2022-04-01 15:05 UTC, ankushdharkar commented on src/context/AuthContext.tsx
> +  loggedInUserData: any;
Why are we using `any` here?

2022-04-01 15:06 UTC, ankushdharkar commented on src/constants/appConstant/url.ts
> +import {githubConfig} from '../../../config/config.sample';
Why is this called `.sample`?

2022-04-01 15:06 UTC, ankushdharkar commented on src/constants/appConstant/url.ts
> +  GITHUB_AUTH: `https://github.com/login/oauth/authorize?client_id=${githubConfig.clientId}`,
Should we check for `clientId` to always exist? How will we know if this is undefined in future?

2022-04-01 15:09 UTC, ankushdharkar commented on src/context/AuthContext.tsx
> +  setLoggedInUserData: (userData: any) => void;
Should context in React contain methods?

2022-04-01 15:26 UTC, ankushdharkar commented on package.json
> +    "transformIgnorePatterns": [
Why is this needed for this PR?

2022-04-16 12:47 UTC, shreya-mishra commented
> The rest of the PR looks good to me but there are a few things to iterate over which are suggested please get them resolved. Some more changes are also needed where at a lot of places we are using any which shall be changed to respective types.

Done in the recent commit.

2022-04-16 12:56 UTC, shreya-mishra commented on src/context/AuthContext.js
> -export default AuthContext;
This is already deleted file. Instead of this, we have AuthContext.tsx

2022-04-16 12:56 UTC, shreya-mishra commented on __tests__/App-test.tsx
> +  const loggedInUserData = {name: 'shreya', profileUrl: ''};
In the test case, we generally provide mock data for the response of the API, because we don't know what will be the response. So that's why I have used this mock data

2022-04-16 12:56 UTC, shreya-mishra commented on __tests__/App-test.tsx
> +                name: 'shreya',
In the test case, we generally provide mock data for the response of the API, because we don't know what will be the response. So that's why I have used this mock data

2022-04-16 12:56 UTC, shreya-mishra commented on __tests__/__snapshots__/HomeScreen-test.tsx.snap
> +            "paddingBottom": 20,
This is the snapshot of the test cases, which is generated automatically.

2022-04-16 12:56 UTC, shreya-mishra commented on package.json
> +    "transformIgnorePatterns": [
While using the testing library Jest the app was crashing so after a lot of google searches we found that we can add this transformIngorePatterns to ignore some of the files in node modules that lead to a crash of the app.

2022-04-16 12:56 UTC, shreya-mishra commented on src/constants/appConstant/url.ts
> +// import {githubConfig} from '../../../config/config'; // you can include client id from readme file in config
It is needed because we are not pushing the config.js file because it contains the GitHub client id which is supposed to be hidden.

2022-04-16 12:56 UTC, shreya-mishra commented on src/constants/appConstant/url.ts
> +import {githubConfig} from '../../../config/config.sample';
resolved in recent commit -

commit link :  https://github.com/Real-Dev-Squad/mobile-app/pull/79/commits/132d211dc12d74a1989bb13f23f523540918945a

2022-04-16 12:56 UTC, shreya-mishra commented on src/constants/appConstant/url.ts
> +  GITHUB_AUTH: `https://github.com/login/oauth/authorize?client_id=${githubConfig.clientId}`,
We have moved the client id to our config file which was not pushed to the repo.
But is it in the readme file? So before testing, we have to include .config with the client id.
If the client id is not there then we can show the alert or something else since the alert doesn't look good. So we can discuss what to show. 

Currently, If the client id is not the user will not able to log in and the response will fail.

2022-04-16 12:56 UTC, shreya-mishra commented on src/context/AuthContext.tsx
> +  loggedInUserData: any;
Fixed in the recent commit.

2022-04-16 12:56 UTC, shreya-mishra commented on src/context/AuthContext.tsx
> +  setLoggedInUserData: (userData: any) => void;
Not able to understand the question properly but if you are talking about type then authContextProviderType is the Type of our createContext which contains functions that are used to change the state of our application. So we have initially defined the function in auth type.

2022-04-16 12:56 UTC, shreya-mishra commented on src/context/AuthContext.tsx
> +export const AuthProvider = ({children}: any) => {
Fixed in the recent commit. Instead of your suggestion, I have created the type initially and then pass it to the react.FC

2022-04-16 12:56 UTC, shreya-mishra commented on src/screens/AuthScreen/Util.ts
> +      .catch(err => Promise.reject(null));
Are we going to display this error to the user in our UI if it is then how it will be? Is it going to be an alert message or a simple text?

2022-04-16 12:56 UTC, shreya-mishra commented on src/screens/ProfileScreen/ProfileScreen.tsx
>    const [response, setResponse] = useState<any>({});
Fixed in recent commit.

2022-04-16 12:56 UTC, shreya-mishra commented on src/screens/ProfileScreen/ProfileScreen.tsx
>    const openModal = useCallback(() => {
We have made the memoized the open modal function so that with every render , the new open modal function should not be created again and again.

2022-04-16 12:56 UTC, shreya-mishra commented on src/screens/ProfileScreen/ProfileScreen.tsx
> -      console.log('error', error);
fixed in recent commit.

2022-04-16 12:56 UTC, shreya-mishra commented on src/screens/AuthScreen/Util.ts
> +      .get(`https://api.realdevsquad.com/users/self`, {
Fixed in recent commit.

2022-04-16 16:24 UTC, DeRaowl approved these changes

2022-04-16 16:25 UTC, merged